language: generic
install:
  - sudo snap install hugo

script:
  - make

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: public
  on:
    branch: master

after_deploy:
  script:
    - curl -d "code=$PULL_CODE" $PULL_ENDPOINT
