name: Build Page and Deploy
on:
    push:
        branches:
            - main
jobs:
    build-page-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Install Hugo
              run: sudo snap install hugo
            - name: Checkout Repo
              uses: actions/checkout@v2
            - name: Build Pages
              run: hugo
            - name: Configure AWS Creds
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-2
            - name: Deploy
              run: aws s3 sync ./public/ s3://blog.notmet.net --delete
